project:
  type: website

execute:
  freeze: true
  
website:
  title: "AD688 Team 1 Spring 2026"
  navbar:
    left:
      - href: about_me.qmd
        text: About Me

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
